services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./conf/templates/:/etc/nginx/conf.d/templates:ro
      - ./conf/static:/etc/nginx/conf.d/static:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./android:/var/www/android:ro
      - ./site:/var/www/site:ro
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    command: >
      /bin/sh -c "envsubst '$$DOMAIN_NAME' < /etc/nginx/conf.d/templates/meetmesh.conf > /etc/nginx/conf.d/meetmesh.conf \
      && cp /etc/nginx/conf.d/static/* /etc/nginx/conf.d \
      && nginx -g 'daemon off;'"

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    environment:
      - DOMAINS=${DOMAINS}
      - EMAIL=${EMAIL}
      - STAGING=${STAGING}
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf/:/etc/letsencrypt:rw
      - ./logs/:/var/log/letsencrypt/
      - ./init-letsencrypt.sh:/init-letsencrypt.sh:ro
    entrypoint: "/bin/sh"
    command: "/./init-letsencrypt.sh"

  app:
    image: meetmesh-server
    ports:
      - 8080:8080

  stripe:
    image: stripe-server
    ports:
      - 8081:8080
